
const products = [
  "Loan Against Property Affordable Home Loan",
  "Loan Against Property",
  "Affordable Home Loan",
  "Prime Home Loan",
  "Affordable Home Loan, Loan Against Property",
  "Personal Loan",
  "Commodity Finance",
  "Secured Business Loan",
  "Unsecured Business Loan",
  "SME Secured / Unsecured Loans",
  "Secured Business Loan",
  "Deposits",
  "CASA",
  "Tractor Loans New / Used",
  "Secured Business Loan Car Loan new/used",
  "Car Loan",
  "Working Capital",
  "Micro LAP",
  "MSME Loans",
  "Branch Banking",
  "Retail Assets",
  "Consumer Goods Loan",
  "Branch Banking",
  "MHCV/ HCV/ LCV / SCV Loans - New & Used",
  "Mortgage Loan",
  "Education Loan",
  "MSME Loans Secured",
  "School Infra Loan / EIL",
  "Loan Against Securities/ Shares",
  "MSME Loans Unsecured",
  "Two Wheelers Loans",
  "Gold Loan",
  "Motor Insurance",
  "Car Loan new/used",
  "Agri Loan",
  "Government Banking",
  "Car Loan new/used",
  "SME Loans Secured",
  "Corporate Banking",
  "Credit Cards",
  "Supply Chain Finance",
  "Vehicle Loan",
  "Life Insurance",
  "NRI Banking",
  "LAP",
  "Auto Loan",
  "Home Loan",
  "Home Loan/LAP",
  "Working Capital",
  "MSME Loans Secured",
  "Deposits",
  "Group Loan",
  "Merchant Banking",
  "Talent Acquisition",
  "NPS",
  "Mutual Funds /Equities",
  "Supply Chain Finance",
];


export default products